export const FETCH_TRENDING = "FETCH_TRENDING";
export const FETCH_TOP = "FETCH_TOP";
export const FETCH_UPCOMING = "FETCH_UPCOMING";
export const FETCH_POPULAR = "FETCH_POPULAR";
export const FETCH_HIGHEST = "FETCH_HIGHEST";
export const FILTER_SEARCH = "FILTER_SEARCH";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_DETAIL = "FETCH_DETAIL";
